(ns qtime.constants
  (:import [java.time ZoneId LocalDate]
           [java.time.temporal ChronoUnit ChronoField]))

(def ^ZoneId utc (ZoneId/of "UTC"))

(def ^LocalDate epoch-day (LocalDate/ofEpochDay 0))

(def chrono-units
  "Mapping of keywords to ChronoUnit"
  {:ns ChronoUnit/NANOS
   :nanos ChronoUnit/NANOS
   :nanosec ChronoUnit/NANOS
   :nanosecs ChronoUnit/NANOS
   :nanosecond ChronoUnit/NANOS
   :nanoseconds ChronoUnit/NANOS
   :us ChronoUnit/MICROS
   :usec ChronoUnit/MICROS
   :usecs ChronoUnit/MICROS
   :usecond ChronoUnit/MICROS
   :useconds ChronoUnit/MICROS
   :micros ChronoUnit/MICROS
   :microsec ChronoUnit/MICROS
   :microsecs ChronoUnit/MICROS
   :microseconds ChronoUnit/MICROS
   :ms ChronoUnit/MILLIS
   :msec ChronoUnit/MILLIS
   :msecs ChronoUnit/MILLIS
   :msecond ChronoUnit/MILLIS
   :mseconds ChronoUnit/MILLIS
   :millis ChronoUnit/MILLIS
   :millisec ChronoUnit/MILLIS
   :millisecs ChronoUnit/MILLIS
   :millisecond ChronoUnit/MILLIS
   :milliseconds ChronoUnit/MILLIS
   :s ChronoUnit/SECONDS
   :sec ChronoUnit/SECONDS
   :secs ChronoUnit/SECONDS
   :second ChronoUnit/SECONDS
   :seconds ChronoUnit/SECONDS
   :min ChronoUnit/MINUTES
   :mins ChronoUnit/MINUTES
   :minute ChronoUnit/MINUTES
   :minutes ChronoUnit/MINUTES
   :hr ChronoUnit/HOURS
   :hrs ChronoUnit/HOURS
   :hour ChronoUnit/HOURS
   :hours ChronoUnit/HOURS
   :half-day ChronoUnit/HALF_DAYS
   :half-days ChronoUnit/HALF_DAYS
   :day ChronoUnit/DAYS
   :days ChronoUnit/DAYS
   :week ChronoUnit/WEEKS
   :weeks ChronoUnit/WEEKS
   :year ChronoUnit/YEARS
   :years ChronoUnit/YEARS
   :decade ChronoUnit/DECADES
   :decades ChronoUnit/DECADES
   :centurie ChronoUnit/CENTURIES
   :centuries ChronoUnit/CENTURIES
   :millennium ChronoUnit/MILLENNIA
   :millennia ChronoUnit/MILLENNIA
   :era ChronoUnit/ERAS
   :eras ChronoUnit/ERAS
   :forever ChronoUnit/FOREVER})

(def keyword-units
  "Back mapping of ChronoUnit constants to keywords"
  {ChronoUnit/NANOS :ns
   ChronoUnit/MICROS :us
   ChronoUnit/MILLIS :ms
   ChronoUnit/SECONDS :s
   ChronoUnit/MINUTES :min
   ChronoUnit/HOURS :hr
   ChronoUnit/HALF_DAYS :half-days 
   ChronoUnit/DAYS :days
   ChronoUnit/WEEKS :weeks
   ChronoUnit/YEARS :years
   ChronoUnit/DECADES :decades
   ChronoUnit/CENTURIES :centuries
   ChronoUnit/MILLENNIA :millennia
   ChronoUnit/ERAS :eras
   ChronoUnit/FOREVER :forever})

(def temporal-fields
  {:aligned-day-of-week-in-month ChronoField/ALIGNED_DAY_OF_WEEK_IN_MONTH
   :aligned-day-of-week-in-year ChronoField/ALIGNED_DAY_OF_WEEK_IN_YEAR
   :aligned-week-of-month ChronoField/ALIGNED_WEEK_OF_MONTH
   :aligned-week-of-year ChronoField/ALIGNED_WEEK_OF_YEAR
   :ampm-of-day ChronoField/AMPM_OF_DAY
   :clock-hour-of-ampm ChronoField/CLOCK_HOUR_OF_AMPM
   :clock-hour-of-day ChronoField/CLOCK_HOUR_OF_DAY
   :day-of-month ChronoField/DAY_OF_MONTH
   :day ChronoField/DAY_OF_MONTH
   :days ChronoField/DAY_OF_MONTH
   :day-of-week ChronoField/DAY_OF_WEEK
   :day-of-year ChronoField/DAY_OF_YEAR
   :epoch-day ChronoField/EPOCH_DAY
   :era ChronoField/ERA
   :hour-of-ampm ChronoField/HOUR_OF_AMPM
   :hour-of-day ChronoField/HOUR_OF_DAY
   :hr ChronoField/HOUR_OF_DAY
   :hrs ChronoField/HOUR_OF_DAY
   :hour ChronoField/HOUR_OF_DAY
   :hours ChronoField/HOUR_OF_DAY
   :instant-seconds ChronoField/INSTANT_SECONDS
   :micro-of-day ChronoField/MICRO_OF_DAY
   :micro-of-second ChronoField/MICRO_OF_SECOND
   :us ChronoField/MICRO_OF_SECOND
   :usec ChronoField/MICRO_OF_SECOND
   :usecs ChronoField/MICRO_OF_SECOND
   :microsec ChronoField/MICRO_OF_SECOND
   :microsecs ChronoField/MICRO_OF_SECOND
   :milli-of-day ChronoField/MILLI_OF_DAY
   :milli-of-second ChronoField/MILLI_OF_SECOND
   :ms ChronoField/MILLI_OF_SECOND
   :msec ChronoField/MILLI_OF_SECOND
   :msecs ChronoField/MILLI_OF_SECOND
   :millisec ChronoField/MILLI_OF_SECOND
   :millisecs ChronoField/MILLI_OF_SECOND
   :minute-of-day ChronoField/MINUTE_OF_DAY
   :minute-of-hour ChronoField/MINUTE_OF_HOUR
   :minute ChronoField/MINUTE_OF_HOUR
   :minutes ChronoField/MINUTE_OF_HOUR
   :m ChronoField/MINUTE_OF_HOUR
   :min ChronoField/MINUTE_OF_HOUR
   :mins ChronoField/MINUTE_OF_HOUR
   :month-of-year ChronoField/MONTH_OF_YEAR
   :nano-of-day ChronoField/NANO_OF_DAY
   :nano-of-second ChronoField/NANO_OF_SECOND
   :ns ChronoField/NANO_OF_SECOND
   :nano ChronoField/NANO_OF_SECOND
   :nanos ChronoField/NANO_OF_SECOND
   :nanosec ChronoField/NANO_OF_SECOND
   :nanosecs ChronoField/NANO_OF_SECOND
   :nanosecond ChronoField/NANO_OF_SECOND
   :nanoseconds ChronoField/NANO_OF_SECOND
   :offset-seconds ChronoField/OFFSET_SECONDS
   :proleptic-month ChronoField/PROLEPTIC_MONTH
   :second-of-day ChronoField/SECOND_OF_DAY
   :second-of-minute ChronoField/SECOND_OF_MINUTE
   :s ChronoField/SECOND_OF_MINUTE
   :sec ChronoField/SECOND_OF_MINUTE
   :secs ChronoField/SECOND_OF_MINUTE
   :second ChronoField/SECOND_OF_MINUTE
   :seconds ChronoField/SECOND_OF_MINUTE
   :year ChronoField/YEAR
   :year-of-era ChronoField/YEAR_OF_ERA})
